name: CI - Build .NET

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restaurar dependencias
        run: dotnet restore EntrevistaApi.sln

      - name: Compilar
        run: dotnet build EntrevistaApi.sln --no-restore --configuration Release